### ISSUE TITLE
Typing for VideoUploadResponse has typo: hsl <-> hls

### ISSUE THREAD

**Issue by ordsen** [apivideo/api.video-typescript-uploader#11]
Hey is there a typo in the typings here:
https://github.com/apivideo/api.video-typescript-uploader/blob/main/dist/src/common.d.ts#L28

The tutorial shows a response object that has an `assets.hls` property, not `.hsl`
https://api.video/blog/tutorials/delegated-uploads

**Comment by olivierapivideo** [comment]
Hi @ordsen , 
We are fixing. Thank you for reporting that.
